apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
image: fariyajs/go-app:5
        ports:
        - containerPort: 8080
