apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 2
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: fariyajs/go-app:latest  # ← Fix indentation + use latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always       # ← For CI/CD auto-updates